module_name: No Captcha reCaptcha Module
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - captcha
  - recaptcha
  - email form
  - security
description_short: The No Captcha reCaptcha module allows you to protect your forms with catchas.
description: description.md
images:
  - image-1.png
license: AFL