module_name: No Captcha reCaptcha Module
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - captcha
  - recaptcha
  - email form
  - security
description_short: Protects your store from spambots and brute force attacks with the new reCAPTCHA by Google.
description: description.md
images:
  - image-1.png
gdpr_compliant: false
license: AFL 3.0
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
